//priority: 1000

// Items added here will get the 'valid_apiary' tag, and be usable as Apiary multiblock walls.
// This is in addition to all blocks that have collision.
const validApiaryBlocks = [
    'glassential:glass_dark',
    'glassential:glass_dark_ethereal',
    'glassential:glass_ethereal',
    'glassential:glass_light',
    'glassential:glass_redstone'
];

const honeyVarieties = [
    'resourcefulbees:catnip_honey',
    'resourcefulbees:honey',
    'resourcefulbees:rainbow_honey',
    'resourcefulbees:redstone_honey',
    'resourcefulbees:emerald_honey',
    'resourcefulbees:diamond_honey',
    'resourcefulbees:illuminating_honey',
    'resourcefulbees:water_honey',
    'resourcefulbees:lapis_honey',
    'resourcefulbees:occultist_honey',
    'resourcefulbees:blazing_crystal_honey',
    'resourcefulbees:energized_steel_honey',
    'resourcefulbees:niotic_crystal_honey',
    'resourcefulbees:nitro_crystal_honey',
    'resourcefulbees:crystal_spirited_honey',
    'resourcefulbees:gaia_honey',
    'resourcefulbees:uraninite_honey',
    'resourcefulbees:elementium_honey',
    'resourcefulbees:manasteel_honey',
    'resourcefulbees:terrasteel_honey',
    'resourcefulbees:xion_honey',
    'resourcefulbees:cloggrum_honey',
    'resourcefulbees:regalium_honey',
    'resourcefulbees:utherium_honey',
    'resourcefulbees:froststeel_honey',
    'resourcefulbees:forgotten_honey',
    'resourcefulbees:steel_honey',
    'resourcefulbees:electrum_honey',
    'resourcefulbees:uranium_honey',
    'resourcefulbees:copper_honey',
    'resourcefulbees:aluminum_honey',
    'resourcefulbees:silver_honey',
    'resourcefulbees:lead_honey',
    'resourcefulbees:nickel_honey',
    'resourcefulbees:osmium_honey',
    'resourcefulbees:cobalt_honey',
    'resourcefulbees:nether_quartz_honey',
    'resourcefulbees:tin_honey',
    'resourcefulbees:zinc_honey',
    'resourcefulbees:fluorite_honey',
    'resourcefulbees:potassium_honey',
    'resourcefulbees:bitumen_honey',
    'resourcefulbees:enderium_honey',
    'resourcefulbees:invar_honey',
    'resourcefulbees:constantan_honey',
    'resourcefulbees:lumium_honey',
    'resourcefulbees:signalum_honey',
    'resourcefulbees:bronze_honey',
    'resourcefulbees:brass_honey',
    'resourcefulbees:starry_honey',
    'resourcefulbees:catnip_honey',
    'resourcefulbees:swift_alloy_honey',
    'resourcefulbees:drenched_iron_honey',
    'resourcefulbees:refined_obsidian_honey',
    'resourcefulbees:refined_glowstone_honey'
];

const combVariants = [
    'gold',
    'forest',
    'occultist',
    'blazing',
    'energized',
    'niotic',
    'nitro',
    'spirited',
    'uraninite',
    'elementium',
    'gaia',
    'manasteel',
    'terrasteel',
    'xion',
    'iron',
    'wither',
    'redstone',
    'emerald',
    'diamond',
    'cloggrum',
    'regalium',
    'utherium',
    'froststeel',
    'forgotten',
    'uranium',
    'steel',
    'electrum',
    'coal',
    'creeper',
    'dragon',
    'ender',
    'lapis',
    'pigman',
    'netherite',
    'rgbee',
    'skeleton',
    'water',
    'zombie',
    'blaze',
    'aluminum',
    'silver',
    'copper',
    'lead',
    'nickel',
    'osmium',
    'cobalt',
    'nether_quartz',
    'tin',
    'zinc',
    'fluorite',
    'potassium',
    'bitumen',
    'invar',
    'enderium',
    'constantan',
    'lumium',
    'signalum',
    'brass',
    'bronze',
    'catnip',
    'starry',
    'swift_alloy',
    'drenched_iron',
    'refined_obsidian',
    'refined_glowstone'
];

const bees = [];

combVariants.forEach((bee) => {
    bees.push(bee)
})

let moreBees = [
    'kitten',
    'oreo',
    'starry_lexxie',
    'yeti',
    'abbee'
];

moreBees.forEach((bee) => {
    bees.push(bee);
});
