onEvent('item.tags', event => {
  event.remove('forge:ores/copper', ['mysticalworld:copper_ore', 'immersiveengineering:ore_copper', 'occultism:copper_ore', 'thermal:copper_ore', 'mekanism:copper_ore', 'create:copper_ore', 'geolosys:malachite_ore', 'tconstruct:copper_ore'])
  event.remove('forge:ingots/copper', ['create:copper_ingot', 'geolosys:copper_ingot', 'projectred-core:copper_ingot', 'occultism:copper_ingot', 'thermal:copper_ingot', 'mekanism:ingot_copper', 'tconstruct:copper_ingot', 'immersiveengineering:ingot_copper', 'mysticalworld:copper_ingot'])
  event.remove('forge:storage_blocks/copper', ['mekanism:block_copper', 'mysticalworld:copper_block', 'immersiveengineering:storage_copper', 'occultism:copper_block', 'thermal:copper_block', 'create:copper_block', 'tconstruct:copper_block'])
  event.remove('forge:dusts/copper', ['pedestals:dustcopper', 'mysticalworld:copper_dust', 'occultism:copper_dust', 'thermal:copper_dust', 'mekanism:dust_copper', 'immersiveengineering:dust_copper'])
  event.remove('forge:nuggets/copper', ['geolosys:copper_nugget', 'mysticalworld:copper_nugget', 'immersiveengineering:nugget_copper', 'occultism:copper_nugget', 'thermal:copper_nugget', 'mekanism:nugget_copper', 'create:copper_nugget', 'tconstruct:copper_nugget'])
  event.remove('forge:plates/copper', ['immersiveengineering:plate_copper', 'thermal:copper_plate', 'create:copper_sheet'])
  event.remove('forge:gears/copper', ['thermal:copper_gear'])
  event.remove('forge:rods/copper', ['createaddition:copper_rod'])
  event.remove('forge:wires/copper', ['createaddition:copper_wire'])

  event.remove('forge:ores/tin', ['mysticalworld:tin_ore', 'mekanism:tin_ore', 'thermal:tin_ore'])
  event.remove('forge:ingots/tin', ['geolosys:tin_ingot', 'projectred-core:tin_ingot', 'mysticalworld:tin_ingot', 'mekanism:ingot_tin', 'thermal:tin_ingot'])
  event.remove('forge:storage_blocks/tin', ['thermal:tin_block', 'mysticalworld:tin_block', 'mekanism:block_tin'])
  event.remove('forge:dusts/tin', ['pedestals:dusttin', 'mysticalworld:tin_dust', 'thermal:tin_dust', 'mekanism:dust_tin'])
  event.remove('forge:nuggets/tin', ['geolosys:tin_nugget', 'mysticalworld:tin_nugget', 'mekanism:nugget_tin', 'thermal:tin_nugget'])
  event.remove('forge:plates/tin', ['thermal:tin_plate'])
  event.remove('forge:gears/tin', ['thermal:tin_gear'])

  event.remove('forge:ores/iron', ['minecraft:iron_ore'])
  event.remove('forge:ores/gold', ['minecraft:gold_ore'])
  event.remove('forge:ores/redstone', ['minecraft:redstone_ore'])
  event.remove('forge:ores/lapis', ['minecraft:lapis_ore'])
  event.remove('forge:ores/diamond', ['minecraft:diamond_ore'])
  event.remove('forge:ores/emerald', ['minecraft:emerald_ore'])
  event.remove('forge:ores/coal', ['minecraft:coal_ore'])
  event.remove('forge:ores/quartz', ['minecraft:nether_quartz_ore'])
})
