
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 614859
	#The name of the modpack
	modpackName = "Chroma Endless"
	#The version of the modpack
	modpackVersion = "1.1.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

