
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "FFffb400"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "FFffcb4f"
	#The color for the background of the tooltip.
	background = "CC262626"
