hiddenTabs = ["enchantment", "worldgen"]
#Range: 1 ~ 4
itemsPerRow = 4
enchantsBlacklist = ["flimflam", "soulBound"]
showDevData = false
dimensionsBlacklist = [-11]
diyData = false
#Range: 1 ~ 4
itemsPerColumn = 4
disableLootManagerReloading = true
