
["UI Button"]
	#X position of the "Open Planner" button. Default: 155
	#Range: -300 ~ 300
	"X Position" = 155
	#Y position of the "Open Planner" button. Default: 8
	#Range: -300 ~ 300
	"Y Position" = 8

[Planner]
	#The scroll direction for paginated lists
	#Allowed Values: UP, DOWN
	"Scroll Direction" = "DOWN"

