// priority: 100

onEvent('recipes', (event) => {
    const idRemovals = [
      // Blocks duplication
      'immersiveengineering:crafting/ingot_aluminum_to_storage_aluminum',
      'thermal:storage/apatite_block',
      'thermal:storage/bitumen_block',
      'create:crafting/materials/brass_block_from_compacting',
      'mekanism:storage_blocks/bronze',
      'thermal:storage/bronze_block',
      'thermal:storage/cinnabar_block',
      'tconstruct:common/materials/cobalt_block_from_ingots',
      'immersiveengineering:crafting/ingot_constantan_to_storage_constantan',
      'thermal:storage/constantan_block',
      'thermal:storage/copper_block',
      'immersiveengineering:crafting/ingot_copper_to_storage_copper',
      'tconstruct:common/materials/copper_block_from_ingots',
      'create:crafting/materials/copper_block_from_compacting',
      'occultism:crafting/copper_block',
      'mekanism:processing/copper/storage_blocks/from_ingots',
      'thermal:storage/electrum_block',
      'immersiveengineering:crafting/ingot_electrum_to_storage_electrum',
      'thermal:storage/enderium_block',
      'mekanism:storage_blocks/fluorite',
      'thermal:storage/invar_block',
      'thermal:storage/lead_block',
      'immersiveengineering:crafting/ingot_lead_to_storage_lead',
      'mekanism:processing/lead/storage_blocks/from_ingots',
      'thermal:storage/lumium_block',
      'immersiveengineering:crafting/ingot_nickel_to_storage_nickel',
      'thermal:storage/nickel_block',
      'mekanism:processing/osmium/storage_blocks/from_ingots',
      'thermal:storage/niter_block',
      'thermal:storage/signalum_block',
      'thermal:storage/silver_block',
      'occultism:crafting/silver_block',
      'immersiveengineering:crafting/ingot_silver_to_storage_silver',
      'mekanism:processing/tin/storage_blocks/from_ingots',
      'thermal:storage/tin_block',
      'immersiveengineering:crafting/ingot_uranium_to_storage_uranium',
      'mekanism:processing/uranium/storage_blocks/from_ingots',
      'create:crafting/materials/zinc_block_from_compacting',

      // Ingots duplication
      'createdeco:netherite_ingot',
      'create:crafting/materials/copper_ingot_from_compacting',
      'tconstruct:common/materials/copper_ingot_from_nuggets',
      'thermal:storage/copper_ingot_from_nuggets',
      'occultism:crafting/copper_ingot_from_nuggets',
      'mekanism:processing/copper/ingot/from_nuggets',
      'immersiveengineering:crafting/nugget_copper_to_ingot_copper',
      'immersiveengineering:crafting/nugget_aluminum_to_ingot_aluminum',
      'occultism:crafting/silver_ingot_from_nuggets',
      'thermal:storage/silver_ingot_from_nuggets',
      'immersiveengineering:crafting/nugget_silver_to_ingot_silver',
      'mekanism:processing/lead/ingot/from_nuggets',
      'thermal:storage/lead_ingot_from_nuggets',
      'immersiveengineering:crafting/nugget_lead_to_ingot_lead',
      'thermal:storage/nickel_ingot_from_nuggets',
      'immersiveengineering:crafting/nugget_nickel_to_ingot_nickel',
      'create:crafting/materials/brass_ingot_from_compacting',
      'thermal:storage/bronze_ingot_from_nuggets',
      'mekanism:processing/bronze/ingot/from_nuggets',
      'tconstruct:common/materials/cobalt_ingot_from_nuggets',
      'thermal:storage/constantan_ingot_from_nuggets',
      'immersiveengineering:crafting/nugget_constantan_to_ingot_constantan',
      'immersiveengineering:crafting/nugget_electrum_to_ingot_electrum',
      'thermal:storage/electrum_ingot_from_nuggets',
      'thermal:storage/enderium_ingot_from_nuggets',
      'thermal:storage/lumium_ingot_from_nuggets',
      'mekanism:processing/osmium/ingot/from_nuggets',
      'thermal:storage/signalum_ingot_from_nuggets',
      'immersiveengineering:crafting/nugget_steel_to_ingot_steel',
      'mekanism:processing/steel/ingot/from_nuggets',
      'thermal:storage/tin_ingot_from_nuggets',
      'mekanism:processing/tin/ingot/from_nuggets',
      'create:crafting/materials/zinc_ingot_from_compacting',
      'bigreactors:crafting/yellorium_storage_to_component',
      'mekanism:processing/uranium/ingot/from_nuggets',
      'immersiveengineering:crafting/nugget_uranium_to_ingot_uranium',
      'bigreactors:yellorium_ingot_to_nugget',
      'thermal:storage/invar_ingot_from_nuggets',

      // Nuggets Duplication
      'immersiveengineering:crafting/ingot_copper_to_nugget_copper',
      'mekanism:processing/copper/nugget_from_ingot',
      'occultism:crafting/copper_nugget',
      'create:crafting/materials/copper_nugget_from_decompacting',
      'create:crafting/materials/copper_nugget_from_decompacting',
      'tconstruct:common/materials/copper_nugget_from_ingot',
      'thermal:storage/copper_nugget_from_ingot',
      'immersiveengineering:crafting/ingot_aluminum_to_nugget_aluminum',
      'thermal:storage/silver_nugget_from_ingot',
      'occultism:crafting/silver_nugget',
      'immersiveengineering:crafting/ingot_silver_to_nugget_silver',
      'immersiveengineering:crafting/ingot_lead_to_nugget_lead',
      'mekanism:processing/lead/nugget/from_ingot',
      'thermal:storage/lead_nugget_from_ingot',
      'thermal:storage/nickel_nugget_from_ingot',
      'immersiveengineering:crafting/ingot_nickel_to_nugget_nickel',
      'mekanism:processing/osmium/nugget/from_ingot',
      'thermal:storage/tin_nugget_from_ingot',
      'mekanism:processing/tin/nugget/from_ingot',
      'create:crafting/materials/zinc_nugget_from_decompacting',
      'tconstruct:common/materials/cobalt_nugget_from_ingot',
      'thermal:storage/bronze_nugget_from_ingot',
      'mekanism:nuggets/bronze',
      'create:crafting/materials/brass_nugget_from_decompacting',
      'immersiveengineering:crafting/ingot_constantan_to_nugget_constantan',
      'thermal:storage/constantan_nugget_from_ingot',
      'thermal:storage/electrum_nugget_from_ingot',
      'immersiveengineering:crafting/ingot_electrum_to_nugget_electrum',
      'mekanism:nuggets/steel',
      'immersiveengineering:crafting/ingot_steel_to_nugget_steel',
      'thermal:storage/invar_nugget_from_ingot',
      'thermal:storage/signalum_nugget_from_ingot',
      'thermal:storage/lumium_nugget_from_ingot',
      'thermal:storage/enderium_nugget_from_ingot'
    ];

    const outputRemovals = [
      'emendatusenigmatica:fluix_block'
    ];

    idRemovals.forEach((id) => {
        event.remove({ id: id });
    });

    outputRemovals.forEach((output) => {
        event.remove({ output: output });
    });
});
