onEvent('recipes', event => {

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_basic_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('emendatusenigmatica:silicon_gem', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:basic_processor', 1))
  .id('refinedstorage:basic_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_advanced_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('emendatusenigmatica:silicon_gem', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:advanced_processor', 1))
  .id('refinedstorage:advanced_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_improved_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('emendatusenigmatica:silicon_gem', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:improved_processor', 1))
  .id('refinedstorage:improved_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_basic_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('minecraft:quartz', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:destruction_core', 1))
  .id('refinedstorage:destruction_core')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('extrastorage:raw_neural_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('emendatusenigmatica:silicon_gem', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('extrastorage:neural_processor', 1))
  .id('extrastorage:neural_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_basic_processor', "input1")
  .requireItem('extendedcrafting:redstone_ingot', "input2")
  .requireItem('minecraft:glowstone_dust', "input3")
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:construction_core', 1))
  .id('refinedstorage:construction_core')
})
