onEvent('recipes', event => {

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_basic_processor')
  .requireItem('extendedcrafting:redstone_ingot')
  .requireItem('emendatusenigmatica:silicon_gem')
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:basic_processor', 1))
  .id('refinedstorage:basic_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_advanced_processor')
  .requireItem('extendedcrafting:redstone_ingot')
  .requireItem('emendatusenigmatica:silicon_gem')
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:advanced_processor', 1))
  .id('refinedstorage:advanced_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_improved_processor')
  .requireItem('extendedcrafting:redstone_ingot')
  .requireItem('emendatusenigmatica:silicon_gem')
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:improved_processor', 1))
  .id('refinedstorage:improved_processor')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('refinedstorage:raw_basic_processor')
  .requireItem('extendedcrafting:redstone_ingot')
  .requireItem('minecraft:quartz')
  .requireEnergyPerTick(100)
  .produceItem(Item.of('refinedstorage:destruction_core', 1))
  .id('refinedstorage:destruction_core')

  event.recipes.custommachinery.custom_machine("custommachinery:inscriber", 240)
  .requireItem('extrastorage:raw_neural_processor')
  .requireItem('extendedcrafting:redstone_ingot')
  .requireItem('emendatusenigmatica:silicon_gem')
  .requireEnergyPerTick(100)
  .produceItem(Item.of('extrastorage:neural_processor', 1))
  .id('extrastorage:neural_processor')
})
